steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '--tag=gcr.io/$PROJECT_ID/az', '.']

# Print version information.
- name: gcr.io/$PROJECT_ID/az
  args: ['--version']

images: ['gcr.io/$PROJECT_ID/az']

