# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://rancher.com/docs/rke/v0.1.x/en/installation/
steps:
- name: 'gcr.io/cloud-builders/wget'
  args: ["https://github.com/rancher/rke/releases/download/v${_RKE_VERSION}/rke_linux-amd64"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/rke:${_RKE_VERSION}',
        '-t', 'gcr.io/$PROJECT_ID/rke',
        '--build-arg', 'RKE_VERSION=${_RKE_VERSION}',
        '--build-arg', 'RKE_VERSION_SHA256SUM=${_RKE_VERSION_SHA256SUM}',
        '.']
substitutions:
  _RKE_VERSION: 0.1.15
  _RKE_VERSION_SHA256SUM: 6687ea0d683a29d6c569cf6ffc7b3a522425b83a1a0b7ea2d402befbd495edaa

images:
- 'gcr.io/$PROJECT_ID/rke:latest'
- 'gcr.io/$PROJECT_ID/rke:$_RKE_VERSION'
