#!/bin/bash

if [[ $# -lt 1 ]] || [[ $# -gt 2 ]]; then
  echo "Usage: $0 <tgz> [target]"
  echo "       <tgz> is a tgz object in a GCS bucket"
  echo "       [target] is a local directory into which you want tgz expanded; defaults to the current directory"
  exit 1
fi

TMP=$(mktemp -d)
localfile="${TMP}/tmp.tgz"
gsutil cp "$1" "${localfile}" || exit

if [[ $# -eq 2 ]]; then
  mkdir -p "${2}" || exit
  cd "${2}" || exit
fi

tar -xzvf "${localfile}" || exit

rm -rf "${TMP}"
