#!/bin/bash

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <tgz> <target>"
  echo "       <tgz> is a tgz object in a GCS bucket"
  echo "       <target> is a local directory into which you want tgz expanded"
  exit 1
fi

TMP=$(mktemp -d)
localfile="${TMP}/tmp.tgz"
gsutil cp "$1" "${localfile}" || exit
tar -xzvf "${localfile}" "${2}" || exit

rm -rf "${TMP}"
