substitutions:
  _VERS: "3.8.0"
  _ARCH: linux-x86_64

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - build
    - "--build-arg=VERS=${_VERS}"
    - "--build-arg=ARCH=${_ARCH}"
    - --tag=gcr.io/${PROJECT_ID}/protoc:${_VERS}-${_ARCH}
    - "."

images:
- "gcr.io/${PROJECT_ID}/protoc"

tags: ['cloud-builders-community']