steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/clojure-jib', '.']
- name: gcr.io/$PROJECT_ID/clojure-jib
  args: ['layers', ':config', '{:main main}']

images: ['gcr.io/$PROJECT_ID/clojure-jib']
tags: ['cloud-builders-community']
