steps:
# Add some checks around example, readme, etc...

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # File that contains failures.
    failure_file=failure.log
    touch ${failure_file}

    # Loop through the builders, and build independently.
    for d in */; do
      echo "Building $d ... "
      (
        gcloud container builds submit $d --config=${d}cloudbuild.yaml > /dev/null 2>&1
        if [[ $? -ne 0 ]]; then
          echo "$d failed" >> ${failure_file}
        fi
      ) &
    done

    wait

    # Check if there is any failure.
    if [[ -s ${failure_file} ]]; then
      echo "Some builds failed:"
      cat ${failure_file}
      echo "Exiting."
      exit 1
    fi

    echo "All builds succeeded."

tags: ['$_PR_NUMBER', '$_REPO_OWNER', '$_REPO', '$_SHA']
