steps:
# Add some checks around examples.

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # File that contains failures.
    failure_file=failure.log
    touch ${failure_file}

    # Loop through the builders, and build independently.
    for d in */; do
      readme="${d}README.md"
      if [[ ! -f "${readme}" ]]; then
        # Note the error but try to build anyway.
        echo "${d}: ${readme} not found." | tee -a ${failure_file}
      fi

      config="${d}cloudbuild.yaml"
      if [[ ! -f "${config}" ]]; then
        echo "${d} failed: ${config} not found." | tee -a ${failure_file}
        continue
      fi

      # The android builder assumes a local installation of Android SDK which is
      # not a valid assumption.
      if [[ "${d}" == "android/" ]]; then
        echo "Skipping $d"
        continue
      fi

      echo "Building $d ... "
      (
        logfile="${d::-1}.log" # Logfile for "foo/" builder is "foo.log".
        gcloud builds submit $d --config=${config} > ${logfile} 2>&1
        if [[ $? -ne 0 ]]; then
          echo "$d failed" | tee -a ${failure_file}
          cat ${logfile}
        fi
      ) &
    done

    wait

    # Check if there is any failure.
    if [[ -s ${failure_file} ]]; then
      echo
      echo "Some builds failed:"
      cat ${failure_file}
      echo "Exiting."
      exit 1
    fi

    echo "All builds succeeded."

tags: ['$_PR_NUMBER', '$_REPO_OWNER', '$_REPO', '$_SHA', 'cloud-builders-community']
