FROM mcr.microsoft.com/windows/servercore:1809 as core
FROM mcr.microsoft.com/windows/nanoserver:1809
ENV CSI_PROXY_PIPE "\\\\.\\pipe\\csipipe"
LABEL description="PD CSI driver"
COPY --from=core /Windows/System32/netapi32.dll /Windows/System32/netapi32.dll
COPY gce-pd-csi-driver.exe /gce-pd-csi-driver.exe

RUN mkdir C:\tmp

USER ContainerAdministrator
ENTRYPOINT ["/gce-pd-csi-driver.exe"]
