# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://www.boot-clj.com
steps:
- name: 'gcr.io/cloud-builders/wget'
  args: ['https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/boot', '-t', 'gcr.io/$PROJECT_ID/boot:latest', '.']

# Test Boot Version
- name: 'gcr.io/$PROJECT_ID/boot'
  args: ['-V']

images:
- 'gcr.io/$PROJECT_ID/boot:latest'
- 'gcr.io/$PROJECT_ID/boot'
