# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#

steps:

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=10.13.0'
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:node-10.13.0'
  # 10.13.0 is tagged :latest
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:latest'
  - '--tag=gcr.io/$PROJECT_ID/nodejs/yarn-puppeteer'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=11.1.0'
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:node-11.1.0'
  # 11.1.0 is tagged :current
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:current'
  - '.'

# Print for each version
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-10.13.0'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-11.1.0'
  args: ['--version']

# Test the cloud builder on the example

- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-10.13.0'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-10.13.0'
  args: ['test:puppeteer']
  dir: 'examples/hello_world'

- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-11.1.0'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-11.1.0'
  args: ['test:puppeteer']
  dir: 'examples/hello_world'

images:
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:latest'
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:current'
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-10.13.0'
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-11.1.0'
- 'gcr.io/$PROJECT_ID/nodejs/yarn-puppeteer'
