# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

substitutions:
  _TERRAFORM_VERSION: 1.6.6
  _TERRAFORM_VERSION_SHA256SUM: d117883fd98b960c5d0f012b0d4b21801e1aea985e26949c2d1ebb39af074f00
  _TERRAGRUNT_VERSION: 0.53.8
  _TERRAGRUNT_VERSION_SHA256SUM: d20345f13c99decbc6018fd836c06fa6a5d4b505d19b04db1138665126df67b5

steps:
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "TERRAFORM_VERSION=${_TERRAFORM_VERSION}"
      - "TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}"
      - "TERRAGRUNT_VERSION=${_TERRAGRUNT_VERSION}"
      - "TERRAGRUNT_VERSION_SHA256SUM=${_TERRAGRUNT_VERSION_SHA256SUM}"
    args:
      - "build"
      - --build-arg
      - TERRAFORM_VERSION=${_TERRAFORM_VERSION}
      - --build-arg
      - TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}
      - --build-arg
      - TERRAGRUNT_VERSION=${_TERRAGRUNT_VERSION}
      - --build-arg
      - TERRAGRUNT_VERSION_SHA256SUM=${_TERRAGRUNT_VERSION_SHA256SUM}
      - --tag
      - "gcr.io/${PROJECT_ID}/terragrunt:${_TERRAFORM_VERSION}-${_TERRAGRUNT_VERSION}"
      - --tag
      - "gcr.io/${PROJECT_ID}/terragrunt:latest"
      - "."
images:
  - "gcr.io/${PROJECT_ID}/terragrunt:${_TERRAFORM_VERSION}-${_TERRAGRUNT_VERSION}"
  - "gcr.io/${PROJECT_ID}/terragrunt:latest"
tags: ["cloud-builders-community"]
