#!/usr/bin/env bash

BUCKET=""
OUT_DIR="."
KEY="cache"
THRESHOLD="50M"
PATHS=()

function print_usage {
  echo "Usage: $0 --out=/cache_dir --key=cache-key --path=/path/to/files/1 --path=/path/to/files/2"
  echo
  echo "Saves the specified paths to a cache file located in the out directory."
  echo
  echo "  -b, --bucket     The cloud storage bucket to upload the cache to. [optional]"
  echo "  -o, --out        The output directory to write the cache to. [optional]"
  echo "  -k, --key        The cache key used for this cache file."
  echo "  -p, --path       The files to store in the cache. Can be repeated."
  echo "  -t, --threshold  The parallel composite upload threshold [default: 50M]"
  echo 
}

for i in "$@"; do
  case $i in
    -b=*|--bucket=*)
      BUCKET="${i#*=}"
      shift
      ;;
    -o=*|--out=*)
      OUT_DIR="${i#*=}"
      shift
      ;;
    -k=*|--key=*)
      KEY="${i#*=}"
      shift
      ;;
    -p=*|--path=*)
      PATHS+="${i#*=} "
      shift
      ;;
    -t=*|--threshold=*)
      THRESHOLD="${i#*=} "
      shift
      ;;
    -h|--help )
      print_usage
      exit 0
      ;;
    *)
      echo "Unknown option: ${i}"
      print_usage
      exit 1
      ;;
  esac
done

if [ -z "$KEY" ] || [ -z "$PATHS" ];then
  print_usage
  exit 1
fi

eval "KEY=$KEY"

CACHE_FILE="${OUT_DIR}/${KEY}.tgz"

echo "Compressing cache to ${CACHE_FILE}..."
tar cpzf "$CACHE_FILE" ${PATHS[@]} -C /

if [ -n "$BUCKET" ];then
  echo "Uploading cache to Google Cloud Storage..."
  gsutil -o GSUtil:parallel_composite_upload_threshold=${THRESHOLD} cp -R "$CACHE_FILE" "$BUCKET"
fi
