# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','gcr.io/${PROJECT_ID}/swift:bionic', '-f', 'Dockerfile-bionic', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','gcr.io/${PROJECT_ID}/swift:xenial', '-f', 'Dockerfile-xenial', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','gcr.io/${PROJECT_ID}/swift:latest-dev', '-f', 'Dockerfile_dev', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','gcr.io/${PROJECT_ID}/swift:4.2', '-f', 'Dockerfile_4-2', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','gcr.io/${PROJECT_ID}/swift:4.2.4', '-f', 'Dockerfile_4-2-4', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','gcr.io/${PROJECT_ID}/swift:5.0-xenial', '-f', 'Dockerfile_5-xenial', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','gcr.io/${PROJECT_ID}/swift:5.0-bionic', '-f', 'Dockerfile_5-bionic', '.']

images: 
  - 'gcr.io/${PROJECT_ID}/swift:bionic'
  - 'gcr.io/${PROJECT_ID}/swift:xenial'
  - 'gcr.io/${PROJECT_ID}/swift:latest-dev'
  - 'gcr.io/${PROJECT_ID}/swift:4.2'
  - 'gcr.io/${PROJECT_ID}/swift:4.2.4'
  - 'gcr.io/${PROJECT_ID}/swift:5.0-xenial'
  - 'gcr.io/${PROJECT_ID}/swift:5.0-bionic'
