#!/bin/sh
sdkmanager -checklicenses
cp -r /build_cache/dot_gradle.zip /
unzip -qq /dot_gradle.zip -d /
cp -r licenses/* $ANDROID_HOME/licenses
license=$1
echo "$license" >> $ANDROID_HOME/licenses/android-sdk-license
shift
gradle $@
status=$?
zip -qqr /build_cache/dot_gradle.zip /root/.gradle
echo "Exit status is: $status"
exit $status
