---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker build'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/replicated-lint', '.']

images: ['gcr.io/$PROJECT_ID/replicated-lint']
tags: ['cloud-builders-community']
