# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flutter', '.']
- name: 'gcr.io/$PROJECT_ID/flutter'
  args: ['--help']

images: ['gcr.io/$PROJECT_ID/flutter']
