steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/firebase', '--build-arg', 'FIREBASE_TOOLS_VERSION=$_FIREBASE_TOOLS_VERSION', '.']
images:
- 'gcr.io/$PROJECT_ID/firebase'
tags: ['cloud-builders-community']

options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _FIREBASE_TOOLS_VERSION: latest
