# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

# See docs at https://www.packer.io/docs/install/index.html
steps:
- name: 'gcr.io/cloud-builders/wget'
  args: ['https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/packer:1.0.0', '-t', 'gcr.io/$PROJECT_ID/packer', '.']

images:
- 'gcr.io/$PROJECT_ID/packer:latest'
- 'gcr.io/$PROJECT_ID/packer:1.0.0'
