# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=1.1.13'
  - '--build-arg'
  - 'commit=b54d75d3'
  - '-t'
  - 'gcr.io/$PROJECT_ID/s2i:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/s2i:1.1.13'
  - '.'
- name: 'gcr.io/$PROJECT_ID/s2i'
  args: ['version']

images:
- 'gcr.io/$PROJECT_ID/s2i:latest'
- 'gcr.io/$PROJECT_ID/s2i:1.1.13'
tags: ['cloud-builders-community']
