steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ng:v1', '-f', 'Dockerfile_v1', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ng:v6', '-f', 'Dockerfile_v6', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ng:v7', '-f', 'Dockerfile_v7', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ng:latest', '-f', 'Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ng', '-f', 'Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ng:next', '-f', 'Dockerfile_next', '.' ]
images:
  - 'gcr.io/$PROJECT_ID/ng:v1'
  - 'gcr.io/$PROJECT_ID/ng:v6'
  - 'gcr.io/$PROJECT_ID/ng:v7'
  - 'gcr.io/$PROJECT_ID/ng:latest'
  - 'gcr.io/$PROJECT_ID/ng'
  - 'gcr.io/$PROJECT_ID/ng:next'