steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/pub", "."]

  # simple sanity check
  - name: "gcr.io/$PROJECT_ID/pub"
    args: ["--version"]

images: ["gcr.io/$PROJECT_ID/pub"]
tags: ["cloud-builders-community"]
