timeout: 900s # 15m
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/internal-tools/cancelot:1.2', '.' ]
images:
- 'us-docker.pkg.dev/$PROJECT_ID/internal-tools/cancelot:1.2'
tags: ['cloud-builders-community']
