# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=v3.1.1'
  - '-t'
  - 'gcr.io/$PROJECT_ID/singularity:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/singularity:v3.1.1'
  - '.'
- name: 'gcr.io/$PROJECT_ID/singularity'
  args: ['version']

images:
- 'gcr.io/$PROJECT_ID/singularity:latest'
- 'gcr.io/$PROJECT_ID/singularity:v3.1.1'
tags: ['cloud-builders-community']
