apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
targetsOnly: gke
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
targetsOnly: repl
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  mysql-pass: '{{repl ConfigOption "mysql_password" | Base64Encode}}'
---
apiVersion: apps/v1
dependencies:
  - filesystem.yaml
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:MYSQL_VERSION
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes-gke:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      volumes-repl:
        - name: mysql-persistent-storage
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: rook-shared-fs
              clusterNamespace: rook-ceph
              path: '/mysql'
