# Run the following command to build this builder:
#   $ gcloud builds submit .

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/docker-reuse:latest", "."]

images:
  - gcr.io/$PROJECT_ID/docker-reuse:latest

tags: ["cloud-builders-community"]
