# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/make', '.']
  dir: 'make'
- name: 'gcr.io/$PROJECT_ID/make'
  args: ['-v']
  dir: 'make'

# Test the example with :latest
- name: 'gcr.io/$PROJECT_ID/make:latest'
  args: ['all']
  dir: 'make/examples'

images:
- 'gcr.io/$PROJECT_ID/make'
