steps:
- name: 'gcr.io/${PROJECT_ID}/swift:latest'
  args: ['--version']
- name: 'gcr.io/${PROJECT_ID}/swift'
  args: ['--version']
- name: 'gcr.io/${PROJECT_ID}/swift:latest-dev'
  args: ['--version']
- name: 'gcr.io/${PROJECT_ID}/swift:4.2'
  args: ['--version']
tags: ['cloud-builders-community']
