steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/helm', '--build-arg', 'HELM_VERSION=v3.0.0', '.']

images: ['gcr.io/$PROJECT_ID/helm']
tags: ['cloud-builders-community']
