---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker build'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/replicated-cli', '.']

images: ['gcr.io/$PROJECT_ID/replicated-cli']
tags: ['cloud-builders-community']
