# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml --substitutions _BUCKET='<bucket name>'
steps:
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['-chdir=${_SOURCE_DIR}', 'init',
    '-backend-config=bucket=${_BUCKET}', '-reconfigure']
  env:
    - "TF_VAR_project=${PROJECT_ID}"
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['-chdir=${_SOURCE_DIR}', 'plan' ]
  env:
    - "TF_VAR_project=${PROJECT_ID}"
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['-chdir=${_SOURCE_DIR}', 'apply', '-auto-approve']
  env:
    - "TF_VAR_project=${PROJECT_ID}"
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['-chdir=${_SOURCE_DIR}', 'destroy', '-auto-approve']
  env:
    - "TF_VAR_project=${PROJECT_ID}"
substitutions:
    _BUCKET: # Provide your own bucket name
    _SOURCE_DIR:
tags: ['cloud-builders-community']
