# Perform a cft command execution based on the `instance.yaml` configuration. This template
# build deletes a GCE image.
#
# See README.md for invocation instructions.
steps:
- name: 'gcr.io/$PROJECT_ID/cft'
  args:
  - --project=$PROJECT_ID
  - delete
  - instance.yaml
